routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', 'TestController@test');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('barang', 'BarangController');
    Route::resource('pelanggan', 'PelangganController');
    Route::resource('transaksi', 'TransaksiController');
    Route::put('transaksi/{id}/fix', 'TransaksiController@fix')->name('transaksi.fix');

    Route::resource('transformasi', 'TransformasiController');
});

app/Pelanggan.php
<?php

namespace App;

use App\Jarak;
use App\Transformasi;
use App\HasilClustering;
use App\TransaksiPemesanan;
use Illuminate\Database\Eloquent\Model;

class Pelanggan extends Model
{
    protected $fillable = ['nama_pelanggan', 'no_telp', 'email', 'alamat', 'diskon'];
    public function transaksiPemesanans() {
        return $this->hasMany(TransaksiPemesanan::class);
    }

    public function transformasi() {
        return $this->hasMany(Transformasi::class);
    }

    public function jarak() {
        return $this->hasMany(Jarak::class);
    }

    public function hasilClustering() {
        return $this->hasOne(HasilClustering::class);
    }
}

app/Http/Controllers/PelangganController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Pelanggan;
use Illuminate\Http\Request;

class PelangganController extends Controller
{
    public function index() {
        $pelanggans = Pelanggan::all();
        return view('pelanggan.index')->with('pelanggans', $pelanggans);
    }

    public function create() {
        return view('pelanggan.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'nama_pelanggan' => 'required',
            'no_telp' => 'required',
            'email' => 'required',
            'alamat' => 'required',
        ]);

        Pelanggan::create([
            'nama_pelanggan' => $request->nama_pelanggan,
            'no_telp' => $request->no_telp,
            'email' =>  $request->email,
            'alamat' => $request->alamat,
            'diskon' => 5
        ]);

        Session::flash('success', 'Berhasil nama pelanggan');
        return redirect()->route('pelanggan.index');
    }

    public function edit($pelanggan) {
        $p = Pelanggan::find($pelanggan);
        return view('pelanggan.edit')->with('pelanggan', $p);
    }

    public function update(Request $request, $pelanggan) {
        $this->validate($request, [
            'nama_pelanggan' => 'required',
            'no_telp' => 'required',
            'email' => 'required',
            'alamat' => 'required',
        ]);

        $p = Pelanggan::find($pelanggan);
        $p->update([
            'nama_pelanggan' => $request->nama_pelanggan,
            'no_telp' => $request->no_telp,
            'email' => $request->email,
            'alamat' => $request->alamat,
            'diskon' => 5
        ]);

        Session::flash('success', 'Berhasil memperbarui pelanggan');
        return redirect()->route('pelanggan.index');
    }

    public function destroy($pelanggan) {
        $p = Pelanggan::find($pelanggan);
        $p->delete();
        Session::flash('success', 'Berhasil menghapus pelanggan');
        return redirect()->back();
    }
}

resources/views/pelanggan/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Tambah Pelanggan</div>

                <div class="panel-body">
                    <form action="{{ route('pelanggan.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <div class="col-md-3"><label>NAMA PELANGGAN</label></div>
                            <div class="col-md-9"><input type="text" name="nama_pelanggan" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>NO TELPON</label></div>
                            <div class="col-md-9"><input type="text" name="no_telp" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>EMAIL</label></div>
                            <div class="col-md-9"><input type="text" name="email" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>ALAMAT</label></div>
                            <div class="col-md-9">
                                <textarea name="alamat" id="alamat" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3"><button type="submit" class="btn btn-block btn-success">SIMPAN</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pelanggan/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Tambah Pelanggan</div>

                <div class="panel-body">
                    <form action="{{ route('pelanggan.update', $pelanggan->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <div class="col-md-3"><label>NAMA PELANGGAN</label></div>
                            <div class="col-md-9"><input type="text" name="nama_pelanggan" value="{{ $pelanggan->nama_pelanggan }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>NO TELPON</label></div>
                            <div class="col-md-9"><input type="text" name="no_telp" value="{{ $pelanggan->no_telp }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>EMAIL</label></div>
                            <div class="col-md-9"><input type="text" name="email" value="{{ $pelanggan->email }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>ALAMAT</label></div>
                            <div class="col-md-9">
                                <textarea name="alamat" id="alamat" cols="30" rows="10" class="form-control">{{ $pelanggan->alamat }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3"><button type="submit" class="btn btn-block btn-success">PERBARUI</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pelanggan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Data Pelanggan</div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>ID PELANGGAN</th>
                            <th>NAMA PELANGGAN</th>
                            <th>NO TELP</th>
                            <th>EMAIL</th>
                            <th>ALAMAT</th>
                            <th>ACTION</th>
                        </thead>
                        <tbody>
                            @foreach($pelanggans as $pelanggan)
                                <tr>
                                    <td>{{ $pelanggan->id }}</td>
                                    <td>{{ $pelanggan->nama_pelanggan }}</td>
                                    <td>{{ $pelanggan->no_telp }}</td>
                                    <td>{{ $pelanggan->email }}</td>
                                    <td>{{ $pelanggan->alamat }}</td>
                                    <td>
                                        <a href="{{ route('pelanggan.edit', $pelanggan->id) }}" class="btn btn-info">edit</a>
                                        <button type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#modalDeleteHapusPelanggan{{ $pelanggan->id }}">
                                            Hapus
                                        </button>

                                        <div class="modal fade" id="modalDeleteHapusPelanggan{{ $pelanggan->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header text-center">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title" id="myModalLabel">Anda yakin ingin menghapus ?</h4>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <form action="{{ route('pelanggan.destroy', $pelanggan->id) }}" method="post">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">BATAL</button>
                                                            <button type="submit" class="btn btn-success">HAPUS</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection