routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', 'TestController@test');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('barang', 'BarangController');
    Route::resource('pelanggan', 'PelangganController');
    Route::resource('transaksi', 'TransaksiController');
    Route::put('transaksi/{id}/fix', 'TransaksiController@fix')->name('transaksi.fix');

    Route::resource('transformasi', 'TransformasiController');
});

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Barang;
use App\Pelanggan;
use App\TransaksiPemesanan;
use Illuminate\Http\Request;
use App\DetailTransaksiPemesanan;

class TransaksiController extends Controller
{
    public function index() {
        $transaksi = TransaksiPemesanan::all();
        $pelanggan = Pelanggan::all();
        return view('transaksi.index')
            ->with('transaksi', $transaksi)
            ->with('pelanggan', $pelanggan);
    }

    public function store(Request $request) {
        $this->validate($request, [
            'pelanggan_id' => 'required'
        ]);

        TransaksiPemesanan::create([
            'pelanggan_id' => $request->pelanggan_id,
            'status' => 0
        ]);

        Session::flash('success', 'Berhasil menambah transaksi pemsanan');
        return redirect()->back();
    }

    public function show($transaksi) {
        $t = TransaksiPemesanan::find($transaksi);
        $barang = Barang::all();
        $detil = $t->detilTransaksi;
        return view('transaksi.show')
            ->with('transaksi', $t)
            ->with('barang', $barang)
            ->with('detil', $detil);
    }

    public function update(Request $request, $transaksi) {
        $this->validate($request, [
            'barang_id' => 'required',
            'jumlah_beli' => 'required'
        ]);

        $t = TransaksiPemesanan::find($transaksi);

        $barang = Barang::find($request->barang_id);
        $hitungTotal = $request->jumlah_beli * $barang->harga_satuan;
        $d = DetailTransaksiPemesanan::create([
            'pesanan_id' => $t->id,
            'barang_id' => $request->barang_id,
            'jumlah_beli' => $request->jumlah_beli,
            'total' => $hitungTotal
        ]);
        if ($t->total == null) {
            $t->total = $hitungTotal;
            $t->save();
        } else {
            $t->total += $hitungTotal;
            $t->save();
        }
        Session::flash('success', 'Berhasil menambah detil transaksi');
        return redirect()->back();
    }

    public function destroy($transaksi) {
        $t = TransaksiPemesanan::find($transaksi);
        $t->delete();
        Session::flash('success', 'Berhasil menghapus transaksi');
        return redirect()->back();
    }

    public function fix(Request $request, $id) {
        $transaksi = TransaksiPemesanan::find($id);
        $transaksi->status = 1;
        $diskon = $request->total * $transaksi->pelanggan->diskon / 100;
        $transaksi->total = $transaksi->total - $diskon;
        $transaksi->save();
        Session::flash('success', 'Transaksi Disimpan');
        return redirect()->route('transaksi.index');
    }
}

resources/views/transaksi/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <button type="button" class="btn btn-success" data-toggle="modal"
                data-target="#modalCreateTransaksi" style="margin-bottom: 10px;">
                Buat Transasksi
            </button>

            <div class="modal fade" id="modalCreateTransaksi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header text-center">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Buat Transaksi Baru</h4>
                        </div>
                        <div class="modal-footer">
                            <form action="{{ route('transaksi.store') }}" method="post">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <select name="pelanggan_id" id="pelanggan_id" class="form-control">
                                        <option value="">Pilih Pelanggan</option>
                                        @foreach($pelanggan as $p)
                                            <option value="{{ $p->id }}">{{ $p->nama_pelanggan }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">BATAL</button>
                                <button type="submit" class="btn btn-success">SIMPAN</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Data Transaksi Pemesanan</div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>ID</th>
                            <th>PELANGGAN</th>
                            <th>PESAN TANGGAL</th>
                            <th>ACTION</th>
                        </thead>
                        <tbody>
                            @foreach($transaksi as $t)
                                <tr>
                                    <td>{{ $t->id }}</td>
                                    <td>{{ $t->pelanggan->nama_pelanggan }}</td>
                                    <td>{{ date('d-m-Y', strtotime($t->created_at)) }}</td>
                                    <td>
                                        <a href="{{ route('transaksi.show', $t->id) }}" class="btn btn-info">Tambah Detil</a>
                                        <button type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#modalDeleteHapusTransaksi{{ $t->id }}">
                                            Hapus
                                        </button>

                                        <div class="modal fade" id="modalDeleteHapusTransaksi{{ $t->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header text-center">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title" id="myModalLabel">Anda yakin ingin menghapus ?</h4>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <form action="{{ route('transaksi.destroy', $t->id) }}" method="post">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">BATAL</button>
                                                            <button type="submit" class="btn btn-success">HAPUS</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transaksi/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Detil Transaksi {{ $transaksi->pelanggan->nama_pelanggan }}</div>

                <div class="panel-body">
                    @if($transaksi->status == 0)
                        <div class="col-md-4">
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br/>
                            @endforeach
                            <form action="#" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <div class="form-group">
                                    <label>NAMA BARANG :</label>
                                    <select name="barang_id" id="barang_id" class="form-control">
                                        <option value="">Pilih Barang</option>
                                        @foreach($barang as $b)
                                            <option value="{{ $b->id }}">{{ $b->nama_barang }} | Harga : {{ $b->harga_satuan }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>JUMLAH BELI :</label>
                                    <input type="text" class="form-control" name="jumlah_beli">
                                </div>
                                <div class="form-group">
                                    <div class="col-md-9 col-md-offset-3"><button type="submit" class="btn btn-block btn-success">TAMBAH</button></div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-8">
                            <table class="table">
                                <thead>
                                    <th>NAMA BARANG</th>
                                    <th>JUMLAH BELI</th>
                                    <th>HARGA SATUAn</th>
                                    <th>TOTAL</th>
                                </thead>
                                <tbody>
                                    @foreach($detil as $d)
                                        <tr>
                                            <td>{{ $d->barang->nama_barang }}</td>
                                            <td>{{ $d->jumlah_beli }}</td>
                                            <td>{{ $d->barang->harga_satuan }}</td>
                                            <td>{{ $d->total }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <table class="table">
                                <thead>
                                    <?php $diskon = $transaksi->total * $transaksi->diskon / 100; ?>
                                    <th>Total : @if($transaksi->total == null) 0 @else {{ $transaksi->total }} @endif</th>
                                    <th>Diskon : {{ $transaksi->diskon }} %</th>
                                    <th>Grand Total : {{ $transaksi->total - $diskon }}</th>
                                    <th>&nbsp;</th>
                                </thead>
                            </table>
                            <form action="{{ route('transaksi.fix', $transaksi->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input type="hidden" name="total" value="{{ $transaksi->total }}">
                                <button class="btn btn-success" type="submit">TRANSAKSI DISIMPAN</button>
                            </form>
                        </div>
                    @else
                        <div class="col-md-12">
                            <table class="table">
                                <thead>
                                    <th>NAMA BARANG</th>
                                    <th>JUMLAH BELI</th>
                                    <th>HARGA SATUAn</th>
                                    <th>TOTAL</th>
                                </thead>
                                <tbody>
                                    @foreach($detil as $d)
                                        <tr>
                                            <td>{{ $d->barang->nama_barang }}</td>
                                            <td>{{ $d->jumlah_beli }}</td>
                                            <td>{{ $d->barang->harga_satuan }}</td>
                                            <td>{{ $d->total }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <table class="table">
                                <thead>
                                    <?php $diskon = $transaksi->total * $transaksi->diskon / 100; ?>
                                    <th>Total : @if($transaksi->total == null) 0 @else {{ $transaksi->total }} @endif</th>
                                    <th>Diskon : {{ $transaksi->diskon }} %</th>
                                    <th>Grand Total : {{ $transaksi->total - $diskon }}</th>
                                    <th>&nbsp;</th>
                                </thead>
                            </table>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection