routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', 'TestController@test');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('barang', 'BarangController');
    Route::resource('pelanggan', 'PelangganController');
    Route::resource('transaksi', 'TransaksiController');
    Route::put('transaksi/{id}/fix', 'TransaksiController@fix')->name('transaksi.fix');

    Route::resource('transformasi', 'TransformasiController');
});

app/Barang.php
<?php

namespace App;

use App\DetailTransaksiPemesanan;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $fillable = ['nama_barang', 'type_barang', 'merek_barang', 'satuan', 'harga_satuan'];

    public function detilTransaksi() {
        return $this->hasMany(DetailTransaksiPemesanan::class);
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Barang;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    public function index() {
        $barangs = Barang::all();
        return view('barang.index')->with('barangs', $barangs);
    }

    public function create() {
        return view('barang.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'nama_barang' => 'required',
            'type_barang' => 'required',
            'merek_barang' => 'required',
            'satuan' => 'required',
            'harga_satuan' => 'required'
        ]);

        Barang::create([
            'nama_barang' => $request->nama_barang,
            'type_barang' => $request->type_barang,
            'merek_barang' => $request->merek_barang,
            'satuan' => $request->satuan,
            'harga_satuan' => $request->harga_satuan
        ]);

        Session::flash('success', 'Berhasil menambahkan barang');
        return redirect()->route('barang.index');
    }

    public function edit($barang) {
        $b = Barang::find($barang);
        return view('barang.edit')->with('barang', $b);
    }

    public function update(Request $request, $barang) {
        $b = Barang::find($barang);
        $this->validate($request, [
            'nama_barang' => 'required',
            'type_barang' => 'required',
            'merek_barang' => 'required',
            'satuan' => 'required',
            'harga_satuan' => 'required'
        ]);

        $b->update([
            'nama_barang' => $request->nama_barang,
            'type_barang' => $request->type_barang,
            'merek_barang' => $request->merek_barang,
            'satuan' => $request->satuan,
            'harga_satuan' => $request->harga_satuan
        ]);

        Session::flash('success', 'Berhasil mengupdate barang');
        return redirect()->route('barang.index');
    }

    public function destroy($barang) {
        $b = Barang::find($barang);
        $b->delete();
        Session::flash('success', 'Berhasil menghapus barang');
        return redirect()->back();
    }
}

resources/views/barang/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Tambah Barang</div>

                <div class="panel-body">
                    <form action="{{ route('barang.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <div class="col-md-3"><label>NAMA BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="nama_barang" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>TYPE BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="type_barang" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>MERK BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="merek_barang" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>SATUAN</label></div>
                            <div class="col-md-9">
                                <select name="satuan" id="satuan" class="form-control">
                                    <option value="">SATUAN...</option>
                                    <option value="BUAH">BUAH</option>
                                    <option value="PASANG">PASANG</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>HARGA</label></div>
                            <div class="col-md-9"><input name="harga_satuan" type="text" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3"><button type="submit" class="btn btn-block btn-success">SIMPAN</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/barang/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Edit Barang</div>

                <div class="panel-body">
                    <form action="{{ route('barang.update', $barang->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <div class="col-md-3"><label>NAMA BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="nama_barang" value="{{ $barang->nama_barang }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>TYPE BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="type_barang" value="{{ $barang->type_barang }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>MERK BARANG</label></div>
                            <div class="col-md-9"><input type="text" name="merek_barang" value="{{ $barang->merek_barang }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>SATUAN</label></div>
                            <div class="col-md-9">
                                <select name="satuan" id="satuan" class="form-control">
                                    <option value="">SATUAN...</option>
                                    <option value="BUAH" @if($barang->satuan == 'BUAH') selected  @endif>BUAH</option>
                                    <option value="PASANG" @if($barang->satuan == 'PASANG') selected  @endif>PASANG</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"><label>HARGA</label></div>
                            <div class="col-md-9"><input name="harga_satuan" type="text" value="{{ $barang->harga_satuan }}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3"><button type="submit" class="btn btn-block btn-success">PERBARUI</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/barang/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Data Barang</div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>ID BARANG</th>
                            <th>NAMA BARANG</th>
                            <th>TYPE BARANG</th>
                            <th>MERK</th>
                            <th>SATUAN</th>
                            <th>HARGA</th>
                            <th>ACTION</th>
                        </thead>
                        <tbody>
                            @foreach($barangs as $barang)
                                <tr>
                                    <td>{{ $barang->id }}</td>
                                    <td>{{ $barang->nama_barang }}</td>
                                    <td>{{ $barang->type_barang }}</td>
                                    <td>{{ $barang->merek_barang }}</td>
                                    <td>{{ $barang->satuan }}</td>
                                    <td>{{ $barang->harga_satuan }}</td>
                                    <td>
                                        <a href="{{ route('barang.edit', $barang->id) }}" class="btn btn-info">edit</a>
                                        <button type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#modalDeleteHapusBarang{{ $barang->id }}">
                                            Hapus
                                        </button>

                                        <div class="modal fade" id="modalDeleteHapusBarang{{ $barang->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header text-center">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title" id="myModalLabel">Anda yakin ingin menghapus ?</h4>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <form action="{{ route('barang.destroy', $barang->id) }}" method="post">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">BATAL</button>
                                                            <button type="submit" class="btn btn-success">HAPUS</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection